name = "portfolio-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
main = ".open-next/worker.js"
assets = { binding = "NEXT_ASSETS", directory = ".open-next/assets" }
pages_build_output_dir = ".open-next/assets"
